### ISSUE TITLE
Meme Maker: Give any image and bounding boxes, get image + text back

### ISSUE THREAD

**Issue by minimaxir** [minimaxir/imgmaker#4]
Requires fixed image size, absolute CSS boxes, TextFit

Some default input schema like:

```yaml
type: meme
image: MonaLisa.png
width: 640
height: 640
css: body {font-family: Impact;}
texts:
  top:
    text: Top text
    x: 0
    y: 0
    w: 640
    h: 320
  bottom:
    text: Bottom Text
    x: 0
    y: 320
    w: 640
    h: 320
```

Then could invoke via:

```python
i.generate('file.yaml', {top: "Override text."})
```
